@startuml
!include styles.puml

package Mapbender <<Frame>> {
  package FeatureType <<Frame>> {
   package Entity <<Frame>> {
      class Feature{
        # id
        # status
      }
      class Schema {
        # id
        # name
      }
      class Schema.name <pk, unique>

    }
    package Component <<Frame>>{
      class FeatureType{
        __ User Management __
        + User getUser():USer
        + setUser(User user)
        __ User Queries __
        + getById(int id): Query
        + add() :

        + remote
      }

    }


  }
}
@enduml