@startuml
skinparam{
    class {
        ArrowColor #666666
        BorderColor #cccccc
        BorderThickness 0.5

    }

    package {
    	ArrowColor SeaGreen
    	BorderColor #999999
    	BackgroundColor #EBFCFF-#FFFFFF
        BorderThickness 1
        PackageFontSize 21
    }
    'shadowing false
}

@enduml